### ISSUE TITLE
udev rules are missing

### ISSUE THREAD

**Issue by m3x1m0m** [mwelling/lofive#6]
[Here](https://github.com/mwelling/lofive/wiki#configuring-host-for-ft2232h-56q-ftdi-uart-breakout) it says, you have to install some udev rules. The mentioned folder does not exist.

**Comment by mwelling** [comment]
Looks like the new SDK uses a standalone toolchain and openocd instead of providing it with the SDK.

If you look at the original lofive branch you will see that it is a submodule there.

Either way you can try to find the file in the standalone SDK or just download it from here:
https://raw.githubusercontent.com/riscv/riscv-openocd/riscv/contrib/60-openocd.rules

`wget https://raw.githubusercontent.com/riscv/riscv-openocd/riscv/contrib/60-openocd.rules`

**Comment by mwelling** [comment]
See updated instructions here:
https://github.com/mwelling/lofive/wiki#configuring-host-for-ft2232h-56q-ftdi-uart-breakout

**Comment by m3x1m0m** [comment]
Very cool! Yeah. I found and copied the udev rules from the standalone openocd shipped by SiFive. Like  

`sudo cp /path/to/openocd/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d`
